name: fR-MCMC
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - openssl==1.1.1h=h516909a_0
  - cffi==1.14.3=py37he30daa8_0
  - numpydoc==1.1.0=py_0
  - sphinxcontrib-qthelp==1.0.3=py_0
  - sphinxcontrib-serializinghtml==1.1.4=py_0
  - parso==0.8.3=pyhd8ed1ab_0
  - mkl==2019.4=243
  - chardet==3.0.4=py37_1003
  - brotlipy==0.7.0=py37h7b6447c_1000
  - importlib-metadata==4.10.0=py37h89c1867_0
  - cryptography==3.1.1=py37h1ba5d50_0
  - tqdm==4.50.2=py_0
  - pytz==2020.1=py_0
  - tomli==2.0.1=pyhd8ed1ab_0
  - backcall==0.2.0=pyh9f0ad1d_0
  - imagesize==1.2.0=py_0
  - curl==7.71.1=hbc83047_1
  - pyzmq==20.0.0=py37h5a562af_1
  - python==3.7.6=h0371630_2
  - matplotlib==3.1.3=py37_0
  - jupyter_core==4.9.1=py37h89c1867_1
  - zlib==1.2.11=h7b6447c_3
  - dbus==1.13.18=hb2f20db_0
  - tbb==2020.3=hfd86e86_0
  - pip==20.2.2=py37_0
  - packaging==20.4=py_0
  - pandas==1.1.1=py37he6710b0_0
  - requests==2.24.0=py_0
  - libssh2==1.9.0=h1ba5d50_1
  - scipy==1.5.2=py37h0b6359f_0
  - wheel==0.35.1=py_0
  - gitpython==3.1.25=pyhd8ed1ab_0
  - gfortran_linux-64==7.2.0=24
  - tk==8.6.10=hbc83047_0
  - attrs==21.4.0=pyhd8ed1ab_0
  - cycler==0.10.0=py37_0
  - ca-certificates==2025.7.14
  - idna==2.10=py_0
  - cftime==1.2.1=py37heb32a55_0
  - blas==1.0=mkl
  - setuptools==50.3.0=py37hb0f4dca_1
  - schwimmbad==0.3.2=py37h89c1867_1
  - statsmodels==0.12.1=py37ha21ca33_1
  - matplotlib-inline==0.1.3=pyhd8ed1ab_0
  - numpy==1.19.1=py37hbc911f0_0
  - ld_impl_linux-64==2.36.1=hea4e1c9_2
  - jinja2==2.11.2=py_0
  - tornado==6.0.4=py37h7b6447c_1
  - freetype==2.10.4=h5ab3b9f_0
  - urllib3==1.25.11=py_0
  - hdf5==1.10.4=hb1b8bf9_0
  - mpi4py==3.0.3=py37hf046da1_1
  - docutils==0.16=py37_1
  - babel==2.8.0=py_0
  - sip==4.19.24=py37he6710b0_0
  - sqlite==3.33.0=h62c20be_0
  - jpeg==9b=habf39ab_1
  - xarray==0.16.1=py_0
  - libsodium==1.0.18=h36c2ea0_1
  - py==1.11.0=pyh6c4a22f_0
  - snowballstemmer==2.0.0=py_0
  - glib==2.56.2=hd408876_0
  - gitdb==4.0.9=pyhd8ed1ab_0
  - seaborn-base==0.11.2=pyhd8ed1ab_0
  - libffi==3.3=he6710b0_2
  - libuuid==1.0.3=h1bed415_2
  - sphinxcontrib-htmlhelp==1.0.3=py_0
  - zipp==3.6.0=pyhd8ed1ab_0
  - netcdf4==1.5.3=py37hbf33ddf_0
  - mpi==1.0=mpich
  - wcwidth==0.2.5=pyh9f0ad1d_2
  - bzip2==1.0.8=h7b6447c_0
  - expat==2.2.10=he6710b0_2
  - typing_extensions==4.0.1=pyha770c72_0
  - mkl-service==2.3.0=py37he904b0f_0
  - python_abi==3.7=2_cp37m
  - backports.functools_lru_cache==1.6.4=pyhd8ed1ab_0
  - pluggy==1.0.0=py37h89c1867_3
  - libxml2==2.9.10=hb55368b_3
  - mpmath==1.1.0=py37_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - pytest==7.1.2=py37h89c1867_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libedit==3.1.20191231=h14c3975_1
  - emcee==3.0.2=pyh5ca1d4c_0
  - patsy==0.5.2=pyhd8ed1ab_0
  - pcre==8.44=he6710b0_0
  - libllvm9==9.0.1=h4a3c616_1
  - krb5==1.18.2=h173b8e3_0
  - pyopenssl==19.1.0=py_1
  - arviz==0.10.0=py_0
  - libxcb==1.14=h7b6447c_0
  - pexpect==4.8.0=pyh9f0ad1d_2
  - smmap==3.0.5=pyh44b312d_0
  - prompt-toolkit==3.0.24=pyha770c72_0
  - entrypoints==0.3=pyhd8ed1ab_1003
  - backports==1.0=py_2
  - h5py==2.10.0=py37h7918eee_0
  - traitlets==5.1.1=pyhd8ed1ab_0
  - alabaster==0.7.12=py37_0
  - ncurses==6.2=he6710b0_1
  - decorator==5.1.0=pyhd8ed1ab_0
  - icu==58.2=he6710b0_3
  - camb==1.1.3=py37h2e358b4_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - numpy-base==1.19.1=py37hfa32c7d_0
  - six==1.15.0=py_0
  - hdf4==4.2.13=h3ca952b_2
  - pygments==2.7.1=py_0
  - pickleshare==0.7.5=py_1003
  - ptyprocess==0.7.0=pyhd3deb0d_0
  - libnetcdf==4.7.3=hb80b6cc_0
  - click==8.0.3=py37h89c1867_1
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - sphinxcontrib-jsmath==1.0.1=py_0
  - fontconfig==2.13.0=h9420a91_0
  - sphinxcontrib-applehelp==1.0.2=py_0
  - seaborn==0.11.2=hd8ed1ab_0
  - sphinx==3.2.1=py_0
  - argcomplete==1.12.3=pyhd8ed1ab_2
  - ipykernel==6.6.0=py37h6531663_0
  - mpich==3.3.2=hc856adb_0
  - jedi==0.18.1=py37h89c1867_0
  - pyparsing==2.4.7=py_0
  - sphinxcontrib-devhelp==1.0.2=py_0
  - matplotlib-base==3.1.3=py37hef1b27d_0
  - jupyter_client==7.1.0=pyhd8ed1ab_0
  - markupsafe==1.1.1=py37h14c3975_1
  - debugpy==1.2.0=py37h745909e_0
  - llvmlite==0.33.0=py37hc6ec683_1
  - pycparser==2.20=py_2
  - intel-openmp==2020.2=254
  - qt==5.9.7=h5867ecd_1
  - numba==0.50.1=py37h0573a6f_1
  - zeromq==4.3.3=h58526e2_3
  - libpng==1.6.37=hbc83047_0
  - xz==5.2.5=h7b6447c_0
  - python-dateutil==2.8.1=py_0
  - certifi==2024.8.30
  - iniconfig==1.1.1=pyh9f0ad1d_0
  - pyqt==5.9.2=py37h22d08a2_1
  - ipython==7.30.1=py37h89c1867_0
  - sympy==1.6.2=py37_0
  - mock==4.0.2=py_0
  - nest-asyncio==1.5.4=pyhd8ed1ab_0
  - libcurl==7.71.1=h20c2e04_1
  - mkl_random==1.1.0=py37hd6b4f25_0
  - pysocks==1.7.1=py37_1
  - readline==7.0=h7b6447c_5
  - gstreamer==1.14.0=hb453b48_1
  - mkl_fft==1.2.0=py37h23d657b_0
  - importlib_metadata==4.10.0=hd8ed1ab_0
  - kiwisolver==1.2.0=py37hfd86e86_0
  - chi2comb
